# Copyright 2017 Insurance Australia Group Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
AWSTemplateFormatVersion: "2010-09-09"
Description: Bakery stack that creates IAM resources that support federation for Environment Burger accounts

Resources:

  GroupNonProdAdmin:
    Type: AWS::IAM::Group
    Properties:
      GroupName: TechAutoNonProdAdmin

  PolicyNonProdAdmin:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: TechAutoNonProdAdmin
      Description: This policy allows to assume a role
      Groups:
        - !Ref GroupNonProdAdmin
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Resource:
              - arn:aws:iam::213618447103:role/NonProd-NonProd-Admin
              - arn:aws:iam::874442481494:role/Stg1-NonProd-Admin
              - arn:aws:iam::658476016886:role/Stg2-NonProd-Admin

  GroupNonProdPowerUser:
    Type: AWS::IAM::Group
    Properties:
      GroupName: TechAutoNonProdPowerUser

  PolicyNonProdPowerUser:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: TechAutoNonProdPowerUser
      Description: This policy allows to assume a role
      Groups:
        - !Ref GroupNonProdPowerUser
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Resource:
              - arn:aws:iam::213618447103:role/NonProd-NonProd-PowerUser
              - arn:aws:iam::874442481494:role/Stg1-NonProd-PowerUser
              - arn:aws:iam::658476016886:role/Stg2-NonProd-PowerUser

  GroupNonProdReadOnly:
    Type: AWS::IAM::Group
    Properties:
      GroupName: TechAutoNonProdReadOnly

  PolicyNonProdReadOnly:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: TechAutoNonProdReadOnly
      Description: This policy allows to assume a role
      Groups:
        - !Ref GroupNonProdReadOnly
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Resource:
              - arn:aws:iam::213618447103:role/NonProd-NonProd-ReadOnly
              - arn:aws:iam::874442481494:role/Stg1-NonProd-ReadOnly
              - arn:aws:iam::658476016886:role/Stg2-NonProd-ReadOnly

  GroupProdAdmin:
    Type: AWS::IAM::Group
    Properties:
      GroupName: TechAutoProdAdmin

  PolicyProdAdmin:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: TechAutoProdAdmin
      Description: This policy allows to assume a role
      Groups:
        - !Ref GroupProdAdmin
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Resource:
              - arn:aws:iam::084555493275:role/Watchmen-Prod-Admin
              - arn:aws:iam::668091071758:role/Woodstock-Prod-Admin

  GroupProdPowerUser:
    Type: AWS::IAM::Group
    Properties:
      GroupName: TechAutoProdPowerUser

  PolicyProdPowerUser:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: TechAutoProdPowerUser
      Description: This policy allows to assume a role
      Groups:
        - !Ref GroupProdPowerUser
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Resource:
              - arn:aws:iam::084555493275:role/Watchmen-Prod-PowerUser
              - arn:aws:iam::668091071758:role/Woodstock-Prod-PowerUser

  GroupProdReadOnly:
    Type: AWS::IAM::Group
    Properties:
      GroupName: TechAutoProdReadOnly

  PolicyProdReadOnly:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: TechAutoProdReadOnly
      Description: This policy allows to assume a role
      Groups:
        - !Ref GroupProdReadOnly
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Resource:
              - arn:aws:iam::084555493275:role/Watchmen-Prod-ReadOnly
              - arn:aws:iam::668091071758:role/Woodstock-Prod-ReadOnly

  GroupMgmtAdmin:
    Type: AWS::IAM::Group
    Properties:
      GroupName: TechAutoMgmtAdmin

  PolicyMgmtAdmin:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: TechAutoMgmtAdmin
      Description: This policy allows to assume a role
      Groups:
        - !Ref GroupMgmtAdmin
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Resource:
              - arn:aws:iam::452161641512:role/Mgmt-Mgmt-Admin

  GroupMgmtPowerUser:
    Type: AWS::IAM::Group
    Properties:
      GroupName: TechAutoMgmtPowerUser

  PolicyMgmtPowerUser:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: TechAutoMgmtPowerUser
      Description: This policy allows to assume a role
      Groups:
        - !Ref GroupMgmtPowerUser
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Resource:
              - arn:aws:iam::452161641512:role/Mgmt-Mgmt-PowerUser

  GroupMgmtReadOnly:
    Type: AWS::IAM::Group
    Properties:
      GroupName: TechAutoMgmtReadOnly

  PolicyMgmtReadOnly:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: TechAutoMgmtReadOnly
      Description: This policy allows to assume a role
      Groups:
        - !Ref GroupMgmtReadOnly
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Resource:
              - arn:aws:iam::452161641512:role/Mgmt-Mgmt-ReadOnly


