# Copyright 2017 Insurance Australia Group Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Burger stack that creates IAM roles that can be federated with Bakery account"

Parameters:

  TeamName:
    Description: "Team name will be prefixed to all IAM resources"
    Type: String
    Default: IAMBakery

  BakeryAccount:
    Description: "Bakery AWS account that provides federation for Burger accounts"
    Type: String
    Default: 111111111111

  Environment:
    Description: "Please enter NonProd, Prod, or Mgmt"
    Type: String
    AllowedValues:
    - NonProd
    - Prod
    - Mgmt

Resources:

  AdminsRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub "arn:aws:iam::${BakeryAccount}:root"
          Action: sts:AssumeRole
      RoleName: !Sub Burger${TeamName}${Environment}Admins
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AdministratorAccess

  PowerUserRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub "arn:aws:iam::${BakeryAccount}:root"
          Action: sts:AssumeRole
      RoleName: !Sub Burger${TeamName}${Environment}PowerUser
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/PowerUserAccess

  ReadOnlyRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub "arn:aws:iam::${BakeryAccount}:root"
          Action: sts:AssumeRole
      RoleName: !Sub Burger${TeamName}${Environment}ReadOnly
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/ReadOnlyAccess
