# Copyright 2017 Insurance Australia Group Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
AWSTemplateFormatVersion: "2010-09-09"
Description: Burger stack that creates IAM roles that can be federated with Bakery account

Parameters:

  BakeryAccount:
    Description: Bakery AWS account that provides federation for Burger accounts
    Type: String
    Default: 900131022284

  AccountName:
    Description: Please enter Burger Account Name, e.g. NonProd, Stg, Mgmt, etc
    Type: String

  Environment:
    Description: Please enter NonProd, Prod or Mgmt
    Type: String
    AllowedValues:
    - NonProd
    - Prod
    - Mgmt

Resources:

  RoleAdmin:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub "arn:aws:iam::${BakeryAccount}:root"
          Action: sts:AssumeRole
      RoleName: !Sub "${AccountName}-${Environment}-Admin"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AdministratorAccess

  RolePowerUser:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub "arn:aws:iam::${BakeryAccount}:root"
          Action: sts:AssumeRole
      RoleName: !Sub "${AccountName}-${Environment}-PowerUser"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/PowerUserAccess

  RoleReadOnly:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub "arn:aws:iam::${BakeryAccount}:root"
          Action: sts:AssumeRole
      RoleName: !Sub "${AccountName}-${Environment}-ReadOnly"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/ReadOnlyAccess


